name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Intro to GitHub Classroom Tests
      id: intro-to-github-classroom-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Intro to GitHub Classroom Tests
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INTRO-TO-GITHUB-CLASSROOM-TESTS_RESULTS: "${{steps.intro-to-github-classroom-tests.outputs.result}}"
      with:
        runners: intro-to-github-classroom-tests
